# Generated by Django 4.1.7 on 2023-02-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_email', models.CharField(max_length=64, unique=True)),
                ('account_pw', models.CharField(max_length=32)),
                ('account_name', models.CharField(max_length=32)),
                ('account_create_dt', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
    ]
