# Generated by Django 4.1.7 on 2023-02-20 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_email',
            field=models.EmailField(max_length=128, unique=True),
        ),
    ]
