# Generated by Django 4.1.7 on 2023-02-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_account_account_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['account_email', 'account_pw', 'account_name', 'account_create_dt']},
        ),
        migrations.AlterField(
            model_name='account',
            name='account_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_pw',
            field=models.CharField(max_length=128),
        ),
    ]
