# Generated by Django 4.1.7 on 2023-02-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_account_options_alter_account_account_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={},
        ),
    ]
